FROM tomcat:alpine

COPY tomcat-users.xml /usr/local/tomcat/conf/
COPY manager-context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml
COPY host-manager-context.xml /usr/local/tomcat/webapps/host-manager/META-INF/context.xml
