requires 'Cpanel::JSON::XS';
requires 'Data::Printer';
requires 'DateTime';
requires 'DBI';
requires 'DBD::SQLite';
requires 'DBIx::Class';
requires 'DBIx::Class::Schema::Loader';
requires 'Digest::MD5::File';
requires 'File::Basename';
requires 'File::Slurper';
requires 'Hash::MoreUtils';
requires 'LWP::UserAgent';
requires 'Moose';
requires 'MooseX::Singleton';
requires 'Pod::Usage';
requires 'strictures', '>=2';
requires 'Test::Class::Moose';
requires 'Test::Most';
