requires 'DateTime';
requires 'DBI';
requires 'DBD::SQLite';
requires 'DBIx::Class';
requires 'DBIx::Class::Schema::Loader';
requires 'Digest::MD5::File';
requires 'Moose';
requires 'MooseX::Singleton';
requires 'strictures', '>=2';
requires 'Test::Class::Moose';
requires 'Test::Most';
